// Code generated by MockGen. DO NOT EDIT.
// Source: ./deps.go
//
// Generated by this command:
//
//	mockgen -source=./deps.go -destination=./deps_mock_test.go -package mcp
//

// Package mcp is a generated GoMock package.
package mcp

import (
	context "context"
	reflect "reflect"

	jira "github.com/dnywonnt/mcp-jira-tempo/internal/jira"
	gomock "go.uber.org/mock/gomock"
)

// MockJiraClient is a mock of JiraClient interface.
type MockJiraClient struct {
	ctrl     *gomock.Controller
	recorder *MockJiraClientMockRecorder
	isgomock struct{}
}

// MockJiraClientMockRecorder is the mock recorder for MockJiraClient.
type MockJiraClientMockRecorder struct {
	mock *MockJiraClient
}

// NewMockJiraClient creates a new mock instance.
func NewMockJiraClient(ctrl *gomock.Controller) *MockJiraClient {
	mock := &MockJiraClient{ctrl: ctrl}
	mock.recorder = &MockJiraClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJiraClient) EXPECT() *MockJiraClientMockRecorder {
	return m.recorder
}

// GetIssue mocks base method.
func (m *MockJiraClient) GetIssue(ctx context.Context, alias, issueKey string) (jira.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssue", ctx, alias, issueKey)
	ret0, _ := ret[0].(jira.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssue indicates an expected call of GetIssue.
func (mr *MockJiraClientMockRecorder) GetIssue(ctx, alias, issueKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssue", reflect.TypeOf((*MockJiraClient)(nil).GetIssue), ctx, alias, issueKey)
}

// Health mocks base method.
func (m *MockJiraClient) Health(ctx context.Context, alias string) (jira.HealthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", ctx, alias)
	ret0, _ := ret[0].(jira.HealthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Health indicates an expected call of Health.
func (mr *MockJiraClientMockRecorder) Health(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockJiraClient)(nil).Health), ctx, alias)
}

// ListIssues mocks base method.
func (m *MockJiraClient) ListIssues(ctx context.Context, req jira.ListIssuesRequest) (jira.ListIssuesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIssues", ctx, req)
	ret0, _ := ret[0].(jira.ListIssuesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIssues indicates an expected call of ListIssues.
func (mr *MockJiraClientMockRecorder) ListIssues(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIssues", reflect.TypeOf((*MockJiraClient)(nil).ListIssues), ctx, req)
}

// LogTime mocks base method.
func (m *MockJiraClient) LogTime(ctx context.Context, req jira.LogTimeRequest) (jira.LogTimeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogTime", ctx, req)
	ret0, _ := ret[0].(jira.LogTimeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogTime indicates an expected call of LogTime.
func (mr *MockJiraClientMockRecorder) LogTime(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTime", reflect.TypeOf((*MockJiraClient)(nil).LogTime), ctx, req)
}

// WhoAmI mocks base method.
func (m *MockJiraClient) WhoAmI(ctx context.Context, alias string) (jira.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WhoAmI", ctx, alias)
	ret0, _ := ret[0].(jira.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WhoAmI indicates an expected call of WhoAmI.
func (mr *MockJiraClientMockRecorder) WhoAmI(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WhoAmI", reflect.TypeOf((*MockJiraClient)(nil).WhoAmI), ctx, alias)
}
